//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopingCartEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Band_Product = new HashSet<Band_Product>();
            this.Images = new HashSet<Image>();
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public int ProductsID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> BrandID { get; set; }
        public string ImageUrl { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public Nullable<double> SalePrice { get; set; }
        public string Detail { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<bool> IsPublished { get; set; }
    
        public virtual ICollection<Band_Product> Band_Product { get; set; }
        public virtual Brand Brand { get; set; }
        public virtual ICollection<Image> Images { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual Category Category { get; set; }
    }
}
